package com.gdg.miagegi.syscohada;

import java.util.ArrayList;
import java.util.HashMap;

import com.gdg.miagegi.syscohada.R;
import com.gdg.miagegi.syscohada.Liste;

import android.os.Bundle;
import android.app.Activity;
import android.content.Intent;
import android.text.Editable;
import android.text.TextWatcher;
import android.view.Menu;
import android.view.MenuItem;
import android.widget.ArrayAdapter;
import android.widget.EditText;
import android.widget.ListView;

public class Liste extends Activity {

	private ListView lv;
    ArrayAdapter<String> adapter;
    EditText inputSearch;
    String edit;
     
     
    // ArrayList for Listview
    ArrayList<HashMap<	String, String>> productList;
	@Override
	protected void onCreate(Bundle savedInstanceState) {
		super.onCreate(savedInstanceState);
		setContentView(R.layout.activity_liste);
		
		final String liste_comptes[] = {
				"10 - CAPITAL",
				"101 -- CAPITAL SOCIAL",
				"1011 --- Capital souscrit, non appelé",
				"1012 --- Capital souscrit, appelé, non versé",
				"1013 --- Capital souscrit, appelé, versé, non amorti",
				"1014 --- Capital souscrit, appelé, versé, amorti ",
				"1018 --- Capital souscrit soumis à des conditions particulières ",
				"102 -- CAPITAL PAR DOTATION ",
				"1021 --- Dotation initiale ",
				"1022 --- Dotations complémentaires ",
				"1028 --- Autres dotations ",
				"103 -- CAPITAL PERSONNEL ",
				"104 -- COMPTE DE L'EXPLOITANT ",
				"1041 --- Apports temporaires ",
				"1042 --- Opérations courantes ",
				"1043 --- Rémunérations, impôts et autres charges personnelles ",
				"1047 --- Prélèvements d’autoconsommation ",
				"1048 --- Autres prélèvements ",
				"105 -- PRIMES LIÉES AUX CAPITAUX PROPRES ",
				"1051 --- Primes d'émission ",
				"1052 --- Primes d'apport ",
				"1053 --- Primes de fusion ",
				"1054 --- Primes de conversion ",
				"1058 --- Autres primes ",
				"106 -- ÉCARTS DE RÉÉVALUATION ",
				"1061 --- Écarts de réévaluation légale ",
				"1062 --- Écarts de réévaluation libre ",
				"109 -- ACTIONNAIRES, CAPITAL SOUSCRIT, NON APPELÉ ",
				"11 - RÉSERVES ",
				"111 -- RÉSERVE LÉGALE",
				"112 -- RÉSERVES STATUTAIRES OU CONTRACTUELLES",
				"113 -- RÉSERVES RÉGLEMENTÉES ",
				"1131 --- Réserves de plus-values nettes à long terme ",
				"1133 --- Réserves consécutives à l'octroi de subventions d'investissement ",
				"1138 --- Autres réserves réglementées ",
				"118 -- AUTRES RÉSERVES ",
				"1181 --- Réserves facultatives ",
				"1188 --- Réserves diverses ",
				"12 -- REPORT À NOUVEAU ",
				"121 -- REPORT À NOUVEAU CRÉDITEUR ",
				"129 --REPORT À NOUVEAU DÉBITEUR ",
				"1291 --- Perte nette à reporter ",
				"1292 --- Perte - Amortissements réputés différés ",
				"13 - RÉSULTAT NET DE L'EXERCICE",
				"130 -- RÉSULTAT EN INSANCE D’AFFECTATION ",
				"1301 --- Résultat en instance d'affectation : Bénéfice ",
				"1309 --- Résultat en instance d'affectation : Perte ",
				"131 -- RÉSULTAT NET : BÉNÉFICE ",
				"132 -- MARGE BRUTE (M.B.) ",
				"1321 --- Marge brute sur marchandises ",
				"1322 --- Marge brute sur matières ",
				"133 -- VALEUR AJOUTÉE (V.A.) ",
				"134 -- EXCÉDENT BRUT D'EXPLOITATION (E.B.E.) ",
				"135 -- RÉSULTAT D'EXPLOITATION (R.E.) ",
				"136 -- RÉSULTAT FINANCIER (R.F.) ",
				"137 -- RÉSULTAT DES ACTIVITÉS ORDINAIRES (R.A.O.) ",
				"138 -- RÉSULTAT HORS ACTIVITÉS ORDINAIRES (R.H.A.O.) ",
				"139 -- RÉSULTAT NET : PERTE ",
				"14 - SUBVENTIONS D'INVESTISSEMENT ",
				"141 -- SUBVENTIONS D'ÉQUIPEMENT A ",
				"1411 --- État ",
				"1412 --- Régions ",
				"1413 --- Départements ",
				"1414 --- Communes et collectivités publiques décentralisées ",
				"1415 --- Entreprises publiques ou mixtes  ",
				"1416 --- Entreprises et organismes privés ",
				"1417 --- Organismes internationaux ",
				"1418 --- Autres ",
				"142 -- SUBVENTIONS D'ÉQUIPEMENT B ",
				"148 -- AUTRES SUBVENTIONS D'INVESTISSEMENT ",
				"15 - PROVISIONS RÉGLEMENTÉESET FONDS ASSIMILÉS ",
				"151 -- AMORTISSEMENTS DÉROGATOIRES ",
				"152 -- PLUS-VALUES DE CESSION À RÉINVESTIR ",
				"153 -- FONDS RÉGLEMENTÉS ",
				"1531 --- Fonds National",
				"1532 --- Prélèvement pour le Budget ",
				"154 -- PROVISION SPÉCIALE DE RÉÉVALUATION ",
				"155 -- PROVISIONS RÉGLEMENTÉES RELATIVES AUX IMMOBILISATIONS ",
				"1551 --- Reconstitution des gisements miniers et pétroliers ",
				"156 -- PROVISIONS RÉGLEMENTÉES RELATIVES AUX STOCKS ",
				"1561 --- Hausse de prix ",
				"1562 --- Fluctuation des cours ",
				"157 -- PROVISIONS POUR INVESTISSEMENT ",
				"158 -- AUTRES PROVISIONS ET FONDS RÉGLEMENTES ",
				"16 - EMPRUNTS ET DETTES ASSIMILÉES ",
				"161 -- EMPRUNTS OBLIGATAIRES",
				"1611 --- Emprunts obligataires ordinaires ",
				"1612 --- Emprunts obligataires convertibles ",
				"1618 --- Autres emprunts obligataires ",
				"162 -- EMPRUNTS ET DETTES AUPRÈS DES ÉTABLISSEMENTS DE CRÉDIT ",
				"163 -- AVANCES REÇUES DE L'ÉTAT ",
				"164 -- AVANCES REÇUES ET COMPTES COURANTS BLOQUÉS",
				"165 -- DÉPÔTS ET CAUTIONNEMENTS RECUS ",
				"1651 --- Dépôts ",
				"1652 --- Cautionnements",
				"166 --- INTÉRÊTS COURUS ",
				"1661 --- sur emprunts obligataires ",
				"1662 --- sur emprunts et dettes auprès des établissements de crédit ",
				"1663 --- sur avances reçues de l'État ",
				"1664 --- sur avances reçues et comptes courants bloqués ",
				"1665 --- sur dépôts et cautionnements reçus ",
				"1667 --- sur avances assorties de conditions particulières ",
				"1668 --- sur autres emprunts et dettes ",
				"167 -- AVANCES ASSORTIES DE CONDITIONS PARTICULIÈRES ",
				"1671 --- Avances bloquées pour augmentation du capital ",
				"1672 --- Avances conditionnées par l'État ",
				"1673 --- Avances conditionnées par les autres organismes africains ",
				"1674 --- Avances conditionnées par les organismes internationaux ",
				"1676 --- Droits du concédant exigibles en nature",
				"168 -- AUTRES EMPRUNTS ET DETTES ",
				"1681 --- Rentes viagères capitalisées ",
				"1682 --- Billets de fonds",
				"1683 --- Dettes consécutives à des titres empruntés ",
				"1684 --- Dettes du concédant exigibles en nature ",
				"1685 --- Emprunts participatifs",
				"1686 --- Participation des travailleurs aux bénéfices ",
				"17 - DETTES DE CRÉDIT - BAIL ET CONTRATS ASSIMILÉS ",
				"172 -- EMPRUNTS ÉQUIVALENTS DE CRÉDIT - BAIL IMMOBILIER",
				"173 -- EMPRUNTS ÉQUIVALENTS DE CRÉDIT - BAIL MOBILIER ",
				"176 -- INTÉRÊTS COURUS",
				"1762 --- sur emprunts équivalents de crédit – bail immobilier",
				"1763 --- sur emprunts équivalents de crédit – bail mobilier ",
				"1768 --- sur emprunts équivalents d’autres contrats ",
				"178 -- EMPRUNTS ÉQUIVALENTSD’AUTRES CONTRATS ",
				"18 - DETTES LIÉES À DES PARTICIPATIONS ET COMPTES DE LIAISON DES ÉTABLISSEMENTS ET SOCIÉTÉS EN PARTICIPATION ",
				"181 -- DETTES LIÉES À DES PARTICIPATIONS ",
				"1811 --- Dettes liées à des participations (groupe) ",
				"1812 --- Dettes liées à des participations (hors groupe) ",
				"182 --- DETTES LIÉES À DES SOCIÉTÉS EN PARTICIPATION ",
				"183 --- INTÉRÊTS COURUS SUR DETTES LIÉES À DES PARTICIPATIONS ",
				"184 --- COMPTES PERMANENTS BLOQUÉS DES ÉTABLISSEMENTS ET SUCCURSALES  ",
				"185 --- COMPTES PERMANENTS NON BLOQUÉS DES ÉTABLISSEMENTS ET SUCCURSALES ",
				"186 -- COMPTES DE LIAISON CHARGES ",
				"187 -- COMPTES DE LIAISON PRODUITS ",
				"188 -- COMPTES DE LIAISON DES SOCIÉTÉS EN PARTICIPATION",
				"19 - PROVISIONS FINANCIERES POUR RISQUES ET CHARGES ",
				"191 -- PROVISIONS POUR LITIGES",
				"192 -- PROVISIONS POUR GARANTIES DONNÉES AUX CLIENTS ",
				"193 -- PROVISIONS POUR PERTES SUR MARCHÉS À ACHÈVEMENT FUTUR ",
				"194 -- PROVISIONS POUR PERTES DE CHANGE",
				"195 -- PROVISIONS POUR IMPÔTS ",
				"196 -- PROVISIONS POUR PENSIONS ET OBLIGATIONS SIMILAIRES ",
				"197 -- PROVISIONS POUR CHARGES À REPARTIR SUR PLUSIEURS EXERCICES ",
				"1971 --- Provisions pour grosses réparations ",
				"198 -- AUTRES PROVISIONS FINANCIÈRES POUR RISQUES ET CHARGES ",
				"1981 --- Provisions pour amendes et pénalités ",
				"1982 --- Provisions pour renouvellement des immobilisations (entreprises concessionnaires) ",
				"1983 --- Provisions de propre assureur ",
				"1988 --- Autres provisions financières pour risques et charges ",
				"20 - CHARGES IMMOBILISÉES ",
				"201 -- FRAIS D'ÉTABLISSEMENT ",
				"2011 --- Frais de constitution  ",
				"2012 --- Frais de prospection ",
				"2013 --- Frais de publicité et de lancement ",
				"2014 --- Frais de fonctionnement antérieurs au démarrage",
				"2015 --- Frais de modification du capital (fusions, scissions, transformations)",
				"2016 --- Frais d'entrée à la Bourse ",
				"2017 --- Frais de restructuration ",
				"2018 --- Frais divers d'établissement ",
				"202 -- CHARGES À RÉPARTIR SUR PLUSIEURS EXERCICES",
				"2021 --- Charges différées ",
				"2022 --- Frais d'acquisition d'immobilisations ",
				"2026 --- Frais d'émission des emprunts ",
				"2028 --- Charges à étaler ",
				"206 -- PRIMES DE REMBOURSEMENT DES OBLIGATIONS ",
				"2061 --- Obligations ordinaires ",
				"2062 --- Obligations convertibles ",
				"2068 --- Autres emprunts obligataires",
				"21 - IMMOBILISATIONS INCORPORELLES ",
				"211 -- FRAIS DE RECHERCHE ET DE DÉVELOPPEMENT ",
				"212 -- BREVETS, LICENCES, CONCESSIONS ET DROITS SIMILAIRES ",
				"213 -- LOGICIELS ",
				"214 -- MARQUES ",
				"215 -- FONDS COMMERCIAL ",
				"216 -- DROIT AU BAIL ",
				"217 -- INVESTISSEMENTS DE CRÉATION",
				"218 -- AUTRES DROITS ET VALEURS INCORPORELS ",
				"219 -- IMMOBILISATIONS INCORPORELLES EN COURS ",
				"2191 --- Frais de recherche etde développement ",
				"2193 --- Logiciels ",
				"2198 --- Autres droits et valeurs incorporels ",
				"22 - TERRAINS ",
				"221 -- TERRAINS AGRICOLES ET FORESTIERS ",
				"2211 --- Terrains d'exploitation agricole ",
				"2212 --- Terrains d'exploitation forestière ",
				"2218 --- Autres terrains ",
				"222 -- TERRAINS NUS ",
				"2221 --- Terrains à bâtir ",
				"2228 --- Autres terrains nus ",
				"223 -- TERRAINS BÂTIS ",
				"2231 --- pour bâtiments industriels et agricoles ",
				"2232 --- pour bâtiments administratifs et commerciaux ",
				"2234 --- pour bâtiments affectés aux autres opérations professionnelles ",
				"2235 --- pour bâtiments affectés aux autres opérations non professionnelles ",
				"2238 --- Autres terrains bâtis ",
				"224 -- TRAVAUX DE MISE EN VALEUR DES TERRAINS ",
				"2241 --- Plantation d'arbres et d'arbustes ",
				"2248 --- Autres travaux ",
				"225 -- TERRAINS DE GISEMENT ",
				"2251 --- Carrières",
				"226 --- TERRAINS AMÉNAGÉS ",
				"2261 --- Parkings ",
				"227 -- TERRAINS MIS EN CONCESSION ",
				"228 -- AUTRES TERRAINS ",
				"2281 --- Terrains des immeubles de rapport ",
				"2285 --- Terrains des logements affectés au personnel ",
				"2288 --- Autres terrains ",
				"229 -- AMÉNAGEMENTS DE TERRAINS EN COURS",
				"2291 --- Terrains agricoles et forestiers",
				"2292 --- Terrains nus ",
				"2295 --- Terrains de gisement ",
				"2298 --- Autres terrains ",
				"23 - BÂTIMENTS, INSTALLATIONS TECHNIQUES ET AGENCEMENTS ",
				"231 -- BÂTIMENTS INDUSTRIELS, AGRICOLES, ADMINISTRATIFS ET COMMERCIAUX SUR SOL PROPRE",
				"2311 --- Bâtiments industriels ",
				"2312 --- Bâtiments agricoles ",
				"2313 --- Bâtiments administratifs et commerciaux  ",
				"2314 --- Bâtiments affectés au logement du personnel ",
				"2315 --- Immeubles de rapport ",
				"232 -- BÂTIMENTS INDUSTRIELS, AGRICOLES, ADMINISTRATIFS ET COMMERCIAUX SUR SOL D’AUTRUI ",
				"2321 --- Bâtiments industriels ",
				"2322 --- Bâtiments agricoles ",
				"2323 --- Bâtiments administratifs et commerciaux ",
				"2324 --- Bâtiments affectés au logement du personnel ",
				"2325 --- Immeubles de rapport ",
				"233 -- OUVRAGES D’INFRASTRUCTURE ",
				"2331 --- Voies de terre ",
				"2332 --- Voies de fer ",
				"2333 --- Voies d’eau ",
				"2334 --- Barrages, Digues ",
				"2335 --- Pistes d’aérodrome ",
				"2338 --- Autres",
				"234 -- INSTALLATIONS TECHNIQUES ",
				"2341 --- Installations complexes spécialisées sur sol propre ",
				"2342 --- Installations complexes spécialisées sur sol d’autrui ",
				"2343 --- Installations à caractère spécifique sur sol propre ",
				"2344 --- Installations à caractère spécifique sur sol d’autrui ",
				"235 -- AMENAGEMENTS DE BUREAUX ",
				"2351 --- Installations générales ",
				"2358 --- Autres ",
				"237 -- BÂTIMENTS INDUSTRIELS, AGRICOLES ET COMMERCIAUX MIS EN CONCESSION ",
				"238 -- AUTRES INSTALLATIONS ET AGENCEMENTS ",
				"239 -- BÂTIMENTS ET INSTALLATIONS EN COURS ",
				"24 - MATÉRIEL ",
				"241 -- MATÉRIEL ET OUTILLAGE INDUSTRIEL ET COMMERCIAL ",
				"2411 --- Matériel industriel ",
				"2412 --- Outillage industriel ",
				"2413 --- Matériel commercial ",
				"2414 --- Outillage commercial ",
				"242 -- MATÉRIEL ET OUTILLAGE AGRICOLE  ",
				"2421 --- Matériel agricole ",
				"2422 --- Outillage agricole ",
				"243 -- MATÉRIEL D’EMBALLAGE RÉCUPÉRABLE ET IDENTIFIABLE",
				"244 -- MATÉRIEL ET MOBILIER ",
				"2441 --- Matériel de bureau ",
				"2442 --- Matériel informatique",
				"2443 --- Matériel bureautique ",
				"2444 --- Mobilier de bureau ",
				"2446 --- Matériel et mobilier des immeubles de rapport ",
				"2447 --- Matériel et mobilier des logements du personnel ",
				"245 -- MATÉRIEL DE TRANSPORT ",
				"2451 --- Matériel automobile ",
				"2452 --- Matériel ferroviaire ",
				"2453 --- Matériel fluvial, lagunaire ",
				"2454 --- Matériel naval ",
				"2455 --- Matériel aérien ",
				"2456 --- Matériel hippomobile ",
				"2458 --- Autres (vélo, mobylette, moto)",
				"246 -- IMMOBILISATIONS ANIMALES ET AGRICOLES ",
				"2461 --- Cheptel, animaux de trait ",
				"2462 --- Cheptel, animaux reproducteurs",
				"2463 --- Animaux de garde ",
				"2465 --- Plantations agricoles ",
				"2468 --- Autres ",
				"247 -- AGENCEMENTS ET AMÉNAGEMENTS DU MATÉRIEL ",
				"248 -- AUTRES MATÉRIELS ",
				"2481 --- Collections et œuvres d’art ",
				"249 -- MATÉRIEL EN COURS ",
				"2491 --- Matériel et outillage industriel et commercial ",
				"2492 --- Matériel et outillage agricole ",
				"2493 --- Matériel d’emballage récupérable et identifiable ",
				"2494 --- Matériel et mobilier de bureau ",
				"2495 --- Matériel de transport ",
				"2496 --- Immobilisations animales et agricoles  ",
				"2497 --- Agencements et aménagements du matériel ",
				"2498 --- Autres matériels ",
				"25 - AVANCES ET ACOMPTES VERSÉS SUR IMMOBILISATIONS ",
				"251 -- AVANCES ET ACOMPTES VERSÉS SUR IMMOBILISATIONS INCORPORELLES ",
				"252 -- AVANCES ET ACOMPTES VERSÉS SUR IMMOBILISATIONS CORPORELLES ",
				"26 - TITRES DE PARTICIPATION ",
				"261 -- TITRES DE PARTICIPATION DANS DES SOCIÉTÉS SOUS CONTRÔLE EXCLUSIF ",
				"261 -- TITRES DE PARTICIPATION DANS DES SOCIÉTÉS SOUS CONTRÔLE EXCLUSIF ",
				"263 -- TITRES DE PARTICIPATION DANS DES SOCIÉTÉS CONFÉRANT UNE INFLUENCE NOTABLE ",
				"265 -- PARTICIPATIONS DANS DES ORGANISMES PROFESSIONNELS ",
				"266 -- PARTS DANS DES GROUPEMENTS D’INTÉRÊT ÉCONOMIQUE (G.I.E.) ",
				"268 -- AUTRES TITRES DE PARTICIPATION ",
				"27 - AUTRES IMMOBLISATIONS FINANCIÈRES",
				"271 -- PRÊTS ET CRÉANCES NON COMMERCIALES",
				"2711 --- Prêts participatifs ",
				"2712 --- Prêts aux associés ",
				"2713 --- Billets de fonds ",
				"2714 --- Titres prêtés ",
				"272 --- PRÊTS AU PERSONNEL ",
				"2721 --- Prêts immobiliers ",
				"2722 --- Prêts mobiliers et d’installation ",
				"2728 --- Autres prêts (frais d’études…) ",
				"273 -- CRÉANCES SUR L’ÉTAT",
				"2731 --- Retenues de garantie ",
				"2733 --- Fonds réglementé ",
				"2738 --- Autres ",
				"274 -- TITRES IMMOBILISÉS",
				"2741 --- Titres immobilisés de l’activitéde portefeuille (T.I.A.P.) ",
				"2742 --- Titres participatifs ",
				"2743 --- Certificats d’investissement ",
				"2744 --- Parts de fonds commun de placement (F.C.P.) ",
				"2748 --- Autres titres immobilisés ",
				"275 -- DÉPÔTS ET CAUTIONNEMENTS VERSÉS ",
				"2751 --- Dépôts pour loyers d’avance ",
				"2752 --- Dépôts pour l’électricité ",
				"2753 --- Dépôts pour l’eau ",
				"2754 --- Dépôts pour le gaz ",
				"2755 --- Dépôts pour le téléphone, le télex, la télécopie ",
				"2756 --- Cautionnements sur marchés publics ",
				"2757 --- Cautionnements sur autres opérations ",
				"2758 --- Autres dépôts et cautionnements ",
				"276 -- INTÉRÊTS COURUS",
				"2761 --- Prêts et créances non commerciales ",
				"2762 --- Prêts au personnel ",
				"2763 --- Créances sur l'Etat ",
				"2764 --- Titres immobilisés ",
				"2765 --- Dépôts et cautionnements versés ",
				"2767 --- Créances rattachées à des participations ",
				"2768 --- Immobilisations financières diverses ",
				"277 -- CRÉANCES RATTACHÉES À DES PARTICIPATIONS ET AVANCES À DES G.I.E.",
				"2771 --- Créances rattachées à des participations (groupe) ",
				"2772 --- Créances rattachées à des participations (hors groupe) ",
				"2773 --- Créances rattachées à des sociétés en participation ",
				"2774 --- Avances à des Groupements d'intérêt économique (G.I.E.) ",
				"278 --- IMMOBILISATIONS FINANCIÈRES DIVERSES ",
				"2781 --- Créances diverses groupe ",
				"2782 --- Créances divers hors groupe ",
				"2785 --- Or et métaux précieux",
				"28 - AMORTISSEMENTS ",
				"281 -- AMORTISSEMENTS DES IMMOBILISATIONS INCORPORELLES ",
				"2811 --- Amortissements des frais de recherche et de développement ",
				"2812 --- Amortissements des brevets, licences, concessions et droits similaires ",
				"2813 --- Amortissements des logiciels  ",
				"2814 --- Amortissements des marques ",
				"2815 --- Amortissements du fonds commercial ",
				"2816 --- Amortissements du droit au bail ",
				"2817 --- Amortissements des investissements de création ",
				"2818 --- Amortissements des autres droits et valeurs incorporels ",
				"282 -- AMORTISSEMENTS DES TERRAINS ",
				"2821 --- Amortissements des terrains agricoles et forestiers ",
				"2824 --- Amortissements des travaux de mise en valeur des terrains ",
				"2825 --- Amortissements des terrains de gisement ",
				"283 -- AMORTISSEMENTS DES BÂTIMENTS, INSTALLATIONS TECHNIQUES ET AGENCEMENTS ",
				"2831 --- Amortissements des bâtiments industriels, agricoles, administratifs et commerciaux sur sol propre",
				"2832 --- Amortissements des bâtiments industriels, agricoles, administratifs et commerciaux sur sol d'autrui ",
				"2833 --- Amortissements des ouvrages d'infrastructure ",
				"2834 --- Amortissements des installations techniques ",
				"2835 --- Amortissements des aménagements de bureaux ",
				"2837 --- Amortissements des bâtiments industriels, agricoles et commerciaux mis en concession ",
				"2838 --- Amortissements des autres installations et agencements ",
				"284 -- AMORTISSEMENTS DU MATÉRIEL",
				"2841 --- Amortissements du matériel et outillage industriel et commercial ",
				"2842 --- Amortissements du matériel et outillage agricole ",
				"2843 --- Amortissements du matériel d'emballage récupérable et identifiable ",
				"2844 --- Amortissements du matériel et mobilier ",
				"2845 --- Amortissements du matériel de transport",
				"2846 --- Amortissements des immobilisations animales et agricoles ",
				"2847 --- Amortissements des agencements etaménagements du matériel ",
"2848 --- Amortissements des autres matériels ",
"29 - PROVISIONS POUR DEPRECIATION ",
"291 -- PROVISIONS POUR DÉPRÉCIATION DES IMMOBILISATIONS INCORPORELLES",
"2912 --- Provisions pour dépréciation des brevets, licences, concessions et droits similaires ",
"2913 --- Provisions pour dépréciation des logiciels ",
"2914 --- Provisions pour dépréciation des marques ",
"2915 --- Provisions pour dépréciation du fonds commercial ",				
"2916 --- Provisions pour dépréciation du droit au bail ",
"2917 --- Provisions pour dépréciation des investissements de création ",
"2918 --- Provisions pour dépréciation des autres droits et valeurs incorporels ",
"2919 --- Provisions pour dépréciation des immobilisations incorporelles en cours ",
"292 -- PROVISIONS POUR DÉPRÉCIATION DES TERRAINS ",
"2921 --- Provisions pour dépréciation des terrains agricoles et forestiers ",
"2922 --- Provisions pour dépréciation des terrains nus ",
"2923 --- Provisions pour dépréciation des terrains bâtis ",
"2924 --- Provisions pour dépréciation des travaux de mise en valeur des terrains ",
"2925 --- Provisions pour dépréciation des terrains de gisement ",
"2926 --- Provisions pour dépréciation des terrains aménagés",
"2927 --- Provisions pour dépréciation des terrains mis en concession",
"2928 --- Provisions pour dépréciation des autres terrains",
"2929 --- Provisions pour dépréciation des aménagements de terrains en cours ",
"293 -- PROVISIONS POUR DÉPRÉCIATION DES BÂTIMENTS, INSTALLATIONS , TECHNIQUES ET AGENCEMENTS", 
"2931 --- Provisions pour dépréciation des bâtiments industriels, agricoles, administratif et commerciaux sur sol propre ",
"2932 --- Provisions pour dépréciation des bâtiments industriels, agricoles, administratif et commerciaux sur sol d'autrui",
"2933 --- Provisions pour dépréciation des ouvrages d'infrastructures", 
"2934 Provisions pour dépréciation des installations techniques", 
"2935 --- Provisions pour dépréciation des aménagements de bureaux ",
"2937 --- Provisions pour dépréciation des bâtiments industriels, agricoles et commerciaux mis en concession ",
"2938 --- Provisions pour dépréciation des autres installations et agencements ",
"2939 --- Provisions pour dépréciation des bâtiments et installations en cours" ,

"294 -- PROVISIONS POUR DÉPRÉCIATION DE MATÉRIEL ",
"2941 --- Provisions pour dépréciation du matériel et outillage industriel et commercial ",
"2942 --- Provisions pour dépréciation du matériel et outillage agricole ",
"2943 --- Provisions pour dépréciation du matériel d'emballage récupérable et identifiable ",
"2944 --- Provisions pour dépréciation du matériel et mobilier ",
"2945 --- Provisions pour dépréciation du matériel de transport ",
"2946 --- Provisions pour dépréciation des immobilisations animales et agricoles", 
"2947 --- Provisions pour dépréciation des agencements et aménagements du matériel ",
"2948 --- Provisions pour dépréciation des autres matériels  ",
"2949 --- Provisions pour dépréciation de matériel en cours ",
"295 -- PROVISIONS POUR DÉPRÉCIATION DES AVANCES ET ACOMPTES VERSÉS SUR IMMOBILISATIONS ",
"2951 --- Provisions pour dépréciation des avances et acomptes versés sur immobilisations incorporelles ",
"2952 --- Provisions pour dépréciation des avances et acomptes versés sur immobilisations corporelles ",
"296 -- PROVISIONS POUR DÉPRÉCIATION DES TITRES DE PARTICIPATION ",
"2961 --- Provisions pour dépréciation des titres de participation dans des sociétés sous contrôle exclusif ",
"2962 --- Provisions pour dépréciation des titres de participation dans les sociétés sous contrôle conjoint ",
"2963 --- Provisions pour dépréciation des titres de participation dans les sociétés conférant une influence notable ",
"2965 --- Provisions pour dépréciation des participations dans des organismes professionnels ",
"2966 --- Provisions pour dépréciation des parts dans des GIE ",
"2968 --- Provisions pour dépréciation des autres titres de participation",
"297 -- PROVISIONS POUR DÉPRÉCIATION DES AUTRES IMMOBILISATIONS FINANCIÈRES",
"2971 --- Provisions pour dépréciation des prêts et créances non commerciales ",
"2972 --- Provisions pour dépréciation des prêts au personnel ",
"2973 --- Provisions pour dépréciation des créances sur l'Etat ",
"2974 --- Provisions pour dépréciation des titres immobilisés ",
"2975 --- Provisions pour dépréciation des dépôts et cautionnements versés ",
"2977 --- Provisions pour dépréciation des créances rattachées à des participations et avances à des GIE ",
"2978 --- Provisions pour dépréciation des créances financières diverses ",
"31 - MARCHANDISES ",
"311 - MARCHANDISES A",
"3111 --- Marchandises A1", 
"3112 --- Marchandises A2 ",
"312 -- MARCHANDISES B ",
"3121 --- Marchandises B1 ",
"3122 --- Marchandises B2 ",
"318 -- MARCHANDISES HORS ACTIVITÉS ORDINAIRES (H.A.O.) ",
"32 - MATIÈRES PREMIÈRES ET FOURNITURES LIÉES",
"321 -- MATIÈRES A ",
"322 -- MATIÈRES B ",
"323 -- FOURNITURES (A,B)", 
"33 - AUTRES APPROVISIONNEMENTS ",
"331 -- MATIÈRES CONSOMMABLES ",
"332 -- FOURNITURES D'ATELIER ET D'USINE ",
"333 -- FOURNITURES DE MAGASIN ",
"334 -- FOURNITURES DE BUREAU ",
"335 -- EMBALLAGES ",
"3351 --- Emballages perdus", 
"3352 --- Emballages récupérables non identifiables ",
"3353 --- Emballages à usage mixte ",
"3358 --- Autres emballages ",
"338 -- AUTRES MATIÈRES ",
"34 - PRODUITS EN COURS ",
"341 -- PRODUITS EN COURS ",
"3411 --- Produits en cours P1 ",
"3412 --- Produits en cours P2 ",
"342 -- TRAVAUX EN COURS ",
"3421 --- Travaux en cours T1",
"3422 --- Travaux en cours T2 ",
"343 -- PRODUITS INTERMÉDIAIRES EN COURS", 
"3431 --- Produits intermédiaires A ",
"3432 --- Produits intermédiaires B ",
"344 -- PRODUITS RÉSIDUELS EN COURS ",
"3441 --- Produits résiduels A ",
"3442 --- Produits résiduels B ",
"35 - SERVICES EN COURS ",
"351 -- ÉTUDES EN COURS",
"3511 --- Études en cours E1",
"3512 --- Études en cours E2",
"352 -- PRESTATIONS DE SERVICES EN COURS ",
"3521 --- Prestations de services S1 ",
"3522 --- Prestations de services S2 ",
"36 - PRODUITS FINIS ",
"361 -- PRODUITS FINIS A ",
"362 -- PRODUITS FINIS B ",
"37 - PRODUITS INTERMÉDIAIRES ET RÉSIDUELS ",
"371 -- PRODUITS INTERMÉDIAIRES ",
"3711 --- Produits intermédiaires A ",
"3712 --- Produits intermédiaires B ",
"372 -- PRODUITS RÉSIDUELS ",
"3721 --- Déchets ",
"3722 --- Rebuts ",
"3723 --- Matières de Récupération ",
"38 - STOCKS EN COURS DE ROUTE, EN CONSIGNATION OU EN DÉPÔT ",
"381 -- MARCHANDISES EN COURS DE ROUTE ",
"38 - MATIÈRES PREMIÈRES ET FOURNITURES LIÉES EN COURS DE ROUTE ",
"383 -- AUTRES APPROVISIONNEMENTS EN COURS DE ROUTE ",
"386 -- PRODUITS FINIS EN COURS DE ROUTE ",
"387 -- STOCK EN CONSIGNATION OU EN DÉPÔT ",
"3871 --- Stock en consignation ",
"3872 --- Stock en dépôt ",
"388 -- STOCK PROVENANT D'IMMOBILISATIONS MISES HORS SERVICE OU AU REBUT ",
"39 - DÉPRÉCIATIONS DES STOCKS ",
"391 -- DÉPRÉCIATIONS DES STOCKS DE MARCHANDISES",
"392 -- DÉPRÉCIATIONS DES STOCKS DE MATIÈRES PREMIÈRES ET FOURNITURES LIÉES",
"393 -- DÉPRÉCIATIONS DES STOCKS D'AUTRES APPOVISIONNEMENTS",
"394 -- DÉPRÉCIATIONS DES PRODUCTIONS EN COURS",
"395 -- DÉPRÉCIATIONS DES SERVICES EN COURS",
"396 -- DÉPRÉCIATIONS DES STOCKS DE PRODUITS FINIS",
"397 -- DÉPRÉCIATIONS DES STOCKS DE PRODUITS INTERMÉDIAIRES ET RÉSIDUELS",
"398 -- DÉPRÉCIATIONS DES STOCKS EN COURS DE ROUTE, EN CONSIGNATION OU EN DÉPÔT",
"40 - FOURNISSEURS ET COMPTES RATTACHÉS ",
"401 -- FOURNISSEURS, DETTES EN COMPTE ",
"4011 --- Fournisseurs ",
"4012 --- Fournisseurs Groupe ",
"4013 --- Fournisseurs sous-traitants ",
"4017 --- Fournisseur, retenues de garantie ",
"402 -- FOURNISSEURS, EFFETS À PAYER ",
"4021 --- Fournisseurs, Effets à payer ",
"4022 --- Fournisseurs - Groupe, Effets à payer ",
"4023 --- Fournisseurs sous-traitants, Effets à payer ",
"408 -- FOURNISSEURS, FACTURES NON PARVENUES ",
"4081 --- Fournisseurs ",
"4082 --- Fournisseurs - Groupe", 
"4083 --- Fournisseurs sous-traitants ",
"4086 --- Fournisseurs, intérêts courus", 
"409 -- FOURNISSEURS DÉBITEURS ",
"4091 --- Fournisseurs avances et acomptes versés ",
"4092 --- Fournisseurs - Groupe avances et acomptes versés ",
"4093 --- Fournisseurs sous-traitants avances et acomptes versés ",
"4094 --- Fournisseurs créances pour emballages et matériels à rendre ",
"4098 --- Rabais, Remises, Ristournes et autres avoirs à obtenir ",
"41 - CLIENTS ET COMPTES RATTACHÉS",
"411 -- CLIENTS ",
"4111 --- Clients ",
"4112 --- Clients - Groupe ",
"4114 --- Clients, État et Collectivités publiques",
"4115 --- Clients, organismes internationaux ",
"4117 --- Client, retenues de garantie ",				
"4118 --- Clients, dégrèvement de Taxes sur la Valeur Ajoutée (T.V.A.) ",
"412 -- CLIENTS, ÉFFETS À RECEVOIR EN PORTEFEUILLE ",
"4121 --- Clients, Effets à recevoir ",
"4122 --- Clients - Groupe, Effets à recevoir ",
"4124 --- État et Collectivités publiques, Effets à recevoir ",
"4125 --- Organismes Internationaux, Effets à recevoir ",
"414 -- CRÉANCES SUR CESSIONSD'IMMOBILISATIONS ",
"4141 --- Créances en compte ",
"4142 --- Effets à recevoir ",
"415 -- CLIENTS, ÉFFETS ESCOMPTÉS NON ÉCHUS ",
"416 -- CRÉANCES CLIENTS LITIGIEUSES OU DOUTEUSES ",
"4161 --- Créances litigieuses ",
"4162 --- Créances douteuses  ",
"418 -- CLIENTS, PRODUITS À RECEVOIR ",
"4181 --- Clients, factures à établir ",
"4186 --- Clients, intérêts courus ",
"419 -- CLIENTS CRÉDITEURS ",
"4191 --- Clients, avances et acomptes reçus ",
"4192 --- Clients - Groupe, avances et acomptes reçus ",
"4194 --- Clients, dettes pour emballages et matériels consignés ",
"4198 --- Rabais, Remises, Ristournes et autres avoirs à accorder", 
"42 - PERSONNEL ",
"421 -- PERSONNEL, AVANCES ET ACOMPTES ",
"4211 --- Personnel, avances ",
"4212 --- Personnel, acomptes ",
"4213 --- Frais avancés et fournitures au personnel ",
"422 -- PERSONNEL, RÉMUNÉRATIONS DUES ",
"423 -- PERSONNEL, OPPOSITIONS, SAISIES-ARRÊTS ",
"4231 --- Personnel, oppositions ",
"4232 --- Personnel, saisies-arrêts ",
"4233 --- Personnel, avis à tiers détenteur ",
"424 -- PERSONNEL, OEUVRES SOCIALES INTERNES ",
"4241 --- Assistance médicale ",
"4242 --- Allocations familiales ",
"4245 --- Organismes sociaux rattachés à l'entreprise ",
"4248 --- Autres oeuvres sociales internes ",
"425 -- REPRÉSENTANTS DU PERSONNEL ",
"4251 --- Délégués du personnel ",
"4252 --- Syndicats et Comités d'entreprises, d'Établissement ",
"4258 --- Autres représentants du personnel ",
"426 -- PERSONNEL, PARTICIPATION AUX BÉNÉFICES ",
"427 -- PERSONNEL – DÉPÔTS ",
"428 -- PERSONNEL, CHARGES À PAYER ET PRODUITS À RECEVOIR ",
"4281 --- Dettes provisionnées pour congés à payer", 
"4286 --- Autres Charges à payer ",
"4287 --- Produits à recevoir ",
"43 - ORGANISMES SOCIAUX ",
"431 -- SÉCURITÉ SOCIALE ",
"4311 --- Prestations familiales ",
"4312 --- Accidents de travail ",
"4313 --- Caisse de retraite obligatoire ",
"4314 --- Caisse de retraite facultative ",
"4318 --- Autres cotisations sociales ",
"432 --- CAISSES DE RETRAITE COMPLÉMENTAIRE ",
"433 -- AUTRES ORGANISMES SOCIAUX ",
"4331 --- Mutuelle ",
"438 -- ORGANISMES SOCIAUX, CHARGES À PAYER ET PRODUITS À RECEVOIR ",
"4381 --- Charges sociales sur gratifications à payer ",
"4382 --- Charges sociales sur congés à payer ",
"4386 --- Autres charges à payer ",
"4387 --- Produits à recevoir ",
"44 - ÉTAT ET COLLECTIVITÉS PUBLIQUES ",
"441 -- ÉTAT, IMPÔT SUR LES BÉNÉFICES ",
"442 -- ÉTAT, AUTRES IMPÔTS ET TAXES ",
"4421 --- Impôts et taxes d'Etat ",
"4422 --- Impôts et taxes pour les collectivités publiques ",
"4423 --- Impôts et taxes recouvrables sur des obligataires ", 
"4424 --- Impôts et taxes recouvrables sur des associés ",
"4426 --- Droits de douane ",
"4428 --- Autres impôts et taxes ",
"443 -- ÉTAT, T.V.A. FACTURÉE ",
"4431 --- T.V.A. facturée sur ventes ",
"4432 --- T.V.A. facturée sur prestations de services ",
"4433 --- T.V.A. facturée sur travaux ",
"4334 --- T.V.A. facturée sur production livrée à soi-même ",
"4335 --- T.V.A. sur factures à établir ",
"444 -- ÉTAT, T.V.A. DUE OU CRÉDIT DE T.V.A. ",
"4441 --- État, T.V.A. due ",
"4449 --- État, crédit de T.V.A. à reporter ",
"445 -- ÉTAT, T.V.A. RÉCUPÉRABLE ", 
"4451 --- T.V.A. récupérable sur immobilisations  ",
"4452 --- T.V.A. récupérable sur achats ",
"4453 --- T.V.A. récupérable sur transport ",
"4454 --- T.V.A. récupérable sur services extérieurs et autres charges ",
"4455 --- T.V.A. récupérable sur factures non parvenues ",
"4456 --- T.V.A. transférée par d'autres entreprises ",
"446 -- ÉTAT, AUTRES TAXES SUR LE CHIFFRE D'AFFAIRES ",
"447 -- ÉTAT, IMPÔTS RETENUS À LA SOURCE ",
"4471 --- Impôt Général sur le revenu ",
"4472 --- Impôts sur salaires ",
"4473 --- Contribution nationale ",
"4474 --- Contribution nationale de solidarité ",
"4478 --- Autres impôts et contributions ",
"448 -- ÉTAT, CHARGES À PAYER ET PRODUITS À RECEVOIR ",
"4486 --- Charges à payer ",
"4487 --- Produits à recevoir ",
"449 --- ÉTAT, CRÉANCES ET DETTES DIVERSES ",
"4491 --- État, obligations cautionnées ",
"4492 --- État, avances et acomptes versés sur impôts ",
"4493 --- État, fonds de dotation à recevoir ",
"4494 --- État, subventions d'équipement à recevoir ",
"4495 --- État, subventions d'exploitation à recevoir", 
"4496 --- État, subventions d'équilibre à recevoir ",
"4499 --- État, fonds réglementé provisionné ",
"45 - ORGANISMES INTERNATIONAUX ",
"451 -- OPÉRATIONS AVEC LES ORGANISMES AFRICAINS ",
"452 -- OPÉRATIONS AVEC LES AUTRES ORGANISMES INTERNATIONAUX ",
"458 -- ORGANISMES INTERNATIONAUX, FONDS DE DOTATION ET SUBVENTIONS À RECEVOIR ",
"4581 --- Organismes internationaux, fonds de dotation à recevoir ",
"4582 --- Organismes internationaux, subventions à recevoir ", 
"46 - ASSOCIÉS ET GROUPE ",
"461 -- ASSOCIÉS, OPÉRATIONS SUR LE CAPITAL ",
"4611 --- Associés apports en nature ",
"4612 --- Associés apports en numéraire  ",
"4613 --- Actionnaires, capital souscrit appelé non versé ",
"4614 --- Associés, capital appelé non versé ",
"4615 --- Associés, versements reçus sur augmentation de capital ",
"4616 --- Associés, versements anticipés ",
"4617 --- Actionnaires défaillants ",
"4618 --- Associés, autres apports ",
"4619 --- Associés, capital à rembourser ",
"462 -- ASSOCIÉS, COMPTES COURANTS ",
"4621 --- Principal ",
"4626 --- Intérêts courus ",
"463 -- ASSOCIÉS, OPÉRATIONS FAITES EN COMMUN ",
"465 -- ASSOCIÉS, DIVIDENDES À PAYER ",
"466 -- GROUPE, COMPTES COURANTS ",
"467 -- ACTIONNAIRES, RESTANT DÛ SUR CAPITAL APPELÉ ",
"47 - DÉBITEURS ET CRÉDITEURS DIVERS ",
"471 -- COMPTES D'ATTENTE ",
"4711 --- Débiteurs divers ",
"4712 --- Créditeurs divers ",
"472 -- VERSEMENTS RESTANT À EFFECTUER SUR TITRES NON LIBÉRÉS ",
"4726 --- Titres de participation ",
"4727 --- Titres immobilisés ",
"4728 --- Titres de placement ",
"474 -- RÉPARTITION PÉRIODIQUE DES CHARGES ET DES PRODUITS ",
"4746 --- Charges ",
"4747 --- Produits ",
"475 -- CRÉANCES SUR TRAVAUX NON ENCORE FACTURABLES ",
"476 -- CHARGES CONSTATÉES D'AVANCE ",
"477 -- PRODUITS CONSTATÉS D'AVANCE ",
"478 -- ÉCARTS DE CONVERSION - ACTIF ",
"4781 --- Diminution des créances ",
"4782 --- Augmentation des dettes ",
"4788 --- Différences compensées par couverture de change ",
"479 -- ÉCARTS DE CONVERSION - PASSIF ",
"4791 --- Augmentation des créances  ",
"4792 --- Diminution des dettes ",
"4798 --- Différences compensées par couverture de change ",
"48 - CRÉANCES ET DETTES HORS ACTIVITÉS ORDINAIRES (HAO)",
"481 -- FOURNISSEURS D'INVESTISSEMENTS ",
"4811 --- Immobilisations incorporelles ",
"4812 --- Immobilisations corporelles ",
"4817 --- Retenues de garantie ",
"4818 --- Factures non parvenues ",
"482 -- FOURNISSEURS D'INVESTISSEMENTS, EFFETS À PAYER ",
"483 -- DETTES SUR ACQUISITION DE TITRES DE PLACEMENT ",
"484 -- AUTRES DETTES HORS ACTIVITES ORDINAIRES (H.A.O.) ",
"485 -- CRÉANCES SUR CESSIONSD'IMMOBILISATIONS ",
"4851 --- En compte ",
"4852 --- Effets à recevoir ",
"4857 --- Retenues de garantie", 
"4858 --- Factures à établir ",
"486 -- CRÉANCES SUR CESSIONS DE TITRES DE PLACEMENT ",
"488 -- AUTRES CRÉANCES HORS ACTIVITÉS ORDINAIRES (H.A.O.) ",
"49 - DÉPRÉCIATIONS ET RISQUES PROVISIONNÉS (TIERS) ",
"490 -- DÉPRÉCIATIONS DES COMPTES FOURNISSEURS ",
"491 -- DÉPRÉCIATIONS DES COMPTES CLIENTS ",
"4911 --- Créances litigieuses ",
"4912 --- Créances douteuses ",
"492 -- DÉPRÉCIATIONS DES COMPTES PERSONNEL ",
"493 -- DÉPRÉCIATIONS DES COMPTES ORGANISMES SOCIAUX ",
"494 -- DÉPRÉCIATIONS DES COMPTES ÉTAT ET COLLECTIVITÉS PUBLIQUES ",
"495 -- DÉPRÉCIATIONS DES COMPTES ORGANISMES INTERNATIONAUX ",
"496 -- DÉPRÉCIATIONS DES COMPTES ASSOCIÉS ET GROUPE ",
"4962 --- Associés, comptes courants ",
"4963 --- Associés, opérations faites en commun ",
"4966 --- Groupe, comptes courants ",
"497 -- DÉPRÉCIATIONS DES COMPTES DÉBITEURS DIVERS ",
"498 -- DÉPRÉCIATIONS DES COMPTES DE CRÉANCES H.A.O. ",
"4981 --- Créances sur cessions d'immobilisations  ",
"4982 --- Créances sur cessions de titres de placement ",
"4983 --- Autres créances H.A.O. ",
"499 -- RISQUES PROVISIONNÉS ",
"4991 --- Sur opérations d'exploitation ",
"4998 --- Sur opérations H.A.O. ",
"50 - TITRES DE PLACEMENT ",
"501 -- TITRES DU TRÉSOR ET BONS DE CAISSE À COURT TERME ",
"5011 --- Titres du Trésor à court terme ",
"5012 --- Titres d'organismes financiers ",
"5013 --- Bons de caisse à court terme ",
"502 -- ACTIONS ",
"5021 --- Actions propres ",
"5022 --- Actions cotées ",
"5023 --- Actions non cotées ",
"5024 --- Actions démembrées (certificats d'investissement ; droits de vote) ",
"5025 --- Autres titres conférant un droit de propriété ",
"503 -- OBLIGATIONS ",
"5031 --- Obligations émises par la société et rachetées par elle ",
"5032 --- Obligations cotées ",
"5033 --- Obligations non cotées ",
"5035 --- Autres titres conférant un droit de créance  ",
"504 -- BONS DE SOUSCRIPTION ",
"5042 --- Bons de souscription d'actions ",
"5043 --- Bons de souscription d'obligations ",
"505 -- TITRES NÉGOCIABLES HORS REGION ",
"506 -- INTÉRÊTS COURUS ",
"5061 --- Titres du Trésor et bons de caisse à court terme ",
"5062 --- Actions ",
"5063 --- Obligations ",
"508 -- AUTRES VALEURS ASSIMILÉES", 
"51 - VALEURS À ENCAISSER ",
"511 -- EFFETS À ENCAISSER ",
"512 -- EFFETS À L'ENCAISSEMENT ",
"513 -- CHÈQUES À ENCAISSER ",
"514 -- CHÈQUES À L'ENCAISSEMENT ",
"515 -- CARTES DE CRÉDIT À ENCAISSER ",
"518 -- AUTRES VALEURS À L'ENCAISSEMENT ",
"5181 --- Warrants ",
"5182 --- Billets de fonds ",
"5185 --- Chèques de voyage ",
"5186 --- Coupons échus ",
"5187 --- Intérêts échus des obligations ",
"52 - BANQUES ",
"521 -- BANQUES LOCALES ",
"5211 --- BANQUES X ",
"5212 --- BANQUE Y ",
"522 -- BANQUES AUTRES ÉTATS REGION ",
"523 -- BANQUES AUTRES ETATS ZONE MONETAIRE ",
"524 -- BANQUES HORS ZONE MONETAIRE ",
"526 -- BANQUES, INTERETS COURUS ",		
"53 - ÉTABLISSEMENTS FINANCIERS ET ASSIMILÉS ",
"531 -- CHÈQUES POSTAUX ",
"532 -- TRÉSOR ",
"533 -- SOCIÉTÉS DE GESTION ET D'INTERMÉDIATION (S.G.I.) ",
"536 -- ETABLISSEMENTS FINANCIERS, INTERETS COURUS ",
"538 -- AUTRES ORGANISMES FINANCIERS ",
"54 - INSTRUMENTS DE TRÉSORERIE ",
"541 -- OPTIONS DE TAUX D'INTÉRÊT ",
"542 -- OPTIONS DE TAUX DE CHANGE ",
"543 -- OPTIONS DE TAUX BOURSIERS ",
"544 -- INSTRUMENTS DE MARCHÉS À TERME ",
"545 -- AVOIRS D'OR ET AUTRES MÉTAUX PRÉCIEUX ",
"56 - BANQUES, CRÉDITS DE TRÉSORERIE ET D'ESCOMPTE ",
"561 -- CRÉDITS DE TRÉSORERIE ",
"564 -- ESCOMPTE DE CRÉDITS DE CAMPAGNE ",
"565 -- ESCOMPTE DE CRÉDITS ORDINAIRES ",
"566 -- BANQUES, CREDITS DE TRESORERIE, INTERETS COURUS ",
"57 - CAISSE ",
"571 -- CAISSE SIÈGE SOCIAL ",
"5711 --- en unités monétaires légales ",
"5712 --- en devises ",
"572 -- CAISSE SUCCURSALE A ",
"5721 --- en unités monétaires légales ",
"5722 --- en devises ",
"573 -- CAISSE SUCCURSALE B ",
"5731 --- en unités monétaires légales ",
"5732 --- en devises ",
"58 - RÉGIES D'AVANCES, ACCRÉDITIFS ET VIREMENTS INTERNES ",
"581 -- RÉGIES D'AVANCE", 
"582 -- ACCRÉDITIFS ",
"585 -- VIREMENTS DE FONDS ",
"588 -- AUTRES VIREMENTS INTERNES ",
"59 - DÉPRÉCIATIONS ET RISQUES PROVISIONNÉS ",
"590 -- DÉPRÉCIATIONS DES TITRES DE PLACEMENT ",
"591 -- DÉPRÉCIATIONS DES TITRES ET VALEURS À ENCAISSER ",
"592 -- DÉPRÉCIATIONS DES COMPTES BANQUES ",
"593 -- DÉPRÉCIATIONS DES COMPTES ÉTABLISSEMENTS FINANCIERS ET ASSIMILÉS ",
"594 -- DÉPRÉCIATIONS DES COMPTES D’INSTRUMENTS DE TRÉSORERIE ",
"599 -- RISQUES PROVISIONNÉS À CARACTÈRE FINANCIER ",
"60 - ACHATS ET VARIATIONS DE STOCKS ",
"601 -- ACHATS DE MARCHANDISES ",
"6011 --- dans la Région ",
"6012 --- hors Région ", 
"6013 --- aux entreprises du groupe dans la Région ",
"6014 --- aux entreprises du groupe hors Région ",
"6019 --- Rabais, Remises et Ristournes obtenus (non ventilés) ",
"602 -- ACHATS DE MATIÈRES PREMIÈRES ET FOURNITURES LIÉES ",
"6021 --- dans la Région", 
"6022 --- hors Région ", 
"6023 --- aux entreprises du groupe dans la Région ",
"6024 --- aux entreprises du groupe hors Région ",
"6029 --- Rabais, Remises et Ristournes obtenus (non ventilés) ",
"603 -- VARIATIONS DES STOCKS DE BIENS ACHETÉS ",
"6031 --- Variations des stocks de marchandises ",
"6032 --- Variations des stocks de matières premières et fournitures liées  ",
"6033 --- Variations des stocks d'autres approvisionnements ",
"604 -- ACHATS STOCKÉS DE MATIÈRES ET FOURNITURES CONSOMMABLES ",
"6041 --- Matières consommables ",
"6042 --- Matières combustibles ",
"6043 --- Produits d'entretien ",
"6044 --- Fournitures d'atelier et d'usine ",
"6046 --- Fournitures de magasin ",
"6047 --- Fournitures de bureau ",
"6049 --- Rabais, Remises et Ristournes obtenus (non ventilés) ",
"605 -- AUTRES ACHATS ",
"6051 --- Fournitures non stockables -Eau ",
"6052 --- Fournitures non stockables - Electricité ",
"6053 --- Fournitures non stockables – Autres énergies ",
"6054 --- Fournitures d'entretien non stockables ",
"6055 --- Fournitures de bureau non stockables ",
"6056 --- Achats de petit matériel et outillage ",
"6057 --- Achats d'études et prestations de services ",
"6058 --- Achats de travaux, matériels et équipements ",
"6059 --- Rabais, Remises et Ristournes obtenus (non ventilés) ",
"608 -- ACHATS D'EMBALLAGES ",
"6081 --- Emballages perdus ",
"6082 --- Emballages récupérables non identifiables ",
"6083 --- Emballages à usage mixte ",
"6089 --- Rabais, Remises et Ristournes obtenus (non ventilés) ",
"61 - TRANSPORTS ",
"611 -- TRANSPORTS SUR ACHATS",
"612 -- TRANSPORTS SUR VENTES ",
"613 -- TRANSPORTS POUR LE COMPTE DE TIERS ",
"614 -- TRANSPORTS DU PERSONNEL ",
"616 -- TRANSPORTS DE PLIS ",
"618 --- AUTRES FRAIS DE TRANSPORT ",
"6181 --- Voyages et déplacements ",
"6182 --- Transports entre établissements ou chantiers ",
"6183 --- Transports administratifs  ",
"62 - SERVICES EXTÉRIEURS A ",
"621 -- SOUS-TRAITANCE GÉNÉRALE ",
"622 -- LOCATIONS ET CHARGES LOCATIVES ",
"6221 --- Locations de terrains ",
"6222 --- Locations de bâtiments ",
"6223 --- Locations de matériels et outillages ",
"6224 --- Malis sur emballages ",
"6225 --- Locations d'emballages ",
"6228 --- Locations et charges locatives diverses ",
"623 -- REDEVANCES DE CRÉDIT-BAIL ET CONTRATS ASSIMILÉS ",
"6232 --- Crédit-bail immobilier ",
"6233 --- Crédit-bail mobilier ",
"6235 --- Contrats assimilés ",
"624 -- ENTRETIEN, RÉPARATIONS ET MAINTENANCE ",
"6241 --- Entretien et réparations des biens immobiliers ",
"6242 --- Entretien et réparations des biens mobiliers ",
"6243 --- Maintenance ",
"6248 --- Autres entretiens et réparations ",
"625 -- PRIMES D'ASSURANCE ",
"6251 --- Assurances multirisques ",
"6252 --- Assurances matériel de transport ",
"6253 --- Assurances risques d'exploitation ",
"6254 --- Assurances responsabilité du producteur ",
"6255 --- Assurances insolvabilité clients ",
"6256 --- Assurances transport sur achats", 
"6257 --- Assurances transport sur ventes", 
"6258 --- Autres primes d'assurances ",
"626 --  ÉTUDES, RECHERCHES ET DOCUMENTATION ",
"6261 --- Études et recherches ",
"6265 --- Documentation générale ",
"6266 --- Documentation technique ",
"627 -- PUBLICITÉ, PUBLICATIONS, RELATIONS PUBLIQUES ",
"6271 --- Annonces, insertions ",
"6272 --- Catalogues, imprimés publicitaires  ",	
"6273 --- Échantillons ",
"6274 --- Foires et expositions", 
"6275 --- Publications ",
"6276 --- Cadeaux à la clientèle ",
"6277 --- Frais de colloques, séminaires, conférences ",
"6278 --- Autres charges de publicité et relations publiques ",
"628 -- FRAIS DE TÉLÉCOMMUNICATIONS ",
"6281 --- Frais de téléphone ",
"6282 --- Frais de télex ",
"6283 --- Frais de télécopie ",
"6288 --- Autres frais de télécommunications ",
"63 - SERVICES EXTÉRIEURS B ",
"631 -- FRAIS BANCAIRES ",
"6311 --- Frais sur titres (achat, vente, garde) ",
"6312 --- Frais sur effets ",
"6313 --- Location de coffres ",
"6315 --- Commissions sur cartes de crédit ",
"6316 --- Frais d'émission d'emprunts", 
"6318 --- Autres frais bancaires ",
"632 -- RÉMUNÉRATIONS D'INTERMÉDIAIRES ET DE CONSEILS ",
"6321 --- Commissions et courtages sur achats ",
"6322 --- Commissions et courtages sur ventes ",
"6323 --- Rémunérations des transitaires ",
"6324 --- Honoraires ",
"6325 --- Frais d'actes et de contentieux ",
"6328 --- Divers frais ",
"633 -- FRAIS DE FORMATION DU PERSONNEL ",
"634 -- REDEVANCES POUR BREVETS, LICENCES, LOGICIELS ET DROITS SIMILAIRES ",
"6342 --- Redevances pour brevets, licences, concessions et droits similaires ",
"6343 --- Redevances pour logiciels ",
"6344 --- Redevances pour marques ",
"635 -- COTISATIONS ",
"6351 --- Cotisations ",
"6358 --- Concours divers  ",
"637 -- RÉMUNÉRATIONS DE PERSONNEL EXTÉRIEUR À L'ENTREPRISE ",
"6371 --- Personnel intérimaire ",
"6372 --- Personnel détaché ou prêté à l'entreprise ",
"638 -- AUTRES CHARGES EXTERNES ",
"6381 --- Frais de recrutement du personnel ",
"6382 --- Frais de déménagement ",
"6383 --- Réceptions ",
"6384 --- Missions ",
"64 - IMPÔTS ET TAXES ",
"641 -- IMPÔTS ET TAXES DIRECTS ",
"6411 --- Impôts fonciers et taxes annexes ",
"6412 --- Patentes, licences et taxes annexes ",
"6413 --- Taxes sur appointements et salaires ",
"6414 --- Taxes d'apprentissage ",
"6415 --- Formation professionnelle continue ",
"6418 --- Autres impôts et taxes directs ",
"645 -- IMPÔTS ET TAXES INDIRECTS ",
"646 -- DROITS D'ENREGISTREMENT ",
"6461 --- Droits de mutation ",
"6462 --- Droits de timbre ",
"6463 --- Taxes sur les véhicules de société ",
"6464 --- Vignettes ",
"6468 --- Autres droits ",
"647 -- PÉNALITÉS ET AMENDES FISCALES ",
"6471 --- Pénalités d'assiette, impôts directs ",
"6472 --- Pénalités d'assiette, impôts indirects ",
"6473 --- Pénalités de recouvrement, impôts directs ",
"6474 --- Pénalités de recouvrement, impôts indirects ",
"6478 --- Autres amendes pénales et fiscales ",
"648 -- AUTRES IMPÔTS ET TAXES ",
"65 - AUTRES CHARGES ",
"651 -- PERTES SUR CRÉANCES CLIENTS ET AUTRES DÉBITEURS ",
"6511 --- Clients ",
"6515 --- Autres débiteurs  ",
"652 -- QUOTE-PART DE RÉSULTAT SUR OPÉRATIONS FAITES EN COMMUN ",
"6521 --- Quote-part transférée de bénéfices (comptabilité du gérant) ",
"6525 --- Pertes imputées par transfert (comptabilité des associés non gérants) ",
"653 -- QUOTE-PART DE RÉSULTAT ANNULÉE SUR EXÉCUTION PARTIELLE DE CONTRATS PLURI-EXERCICES ",
"654 -- VALEUR COMPTABLE DES CESSIONS COURANTES D'IMMOBILISATIONS ",
"658 -- CHARGES DIVERSES ",
"6581 --- Jetons de présence et autres rémunérations d'administrateurs ",
"6582 --- Dons ",
"6583 --- Mécénat ",
"659 -- CHARGES PROVISIONNÉES D'EXPLOITATION ",
"6591 --- sur risques à court terme ",
"6593 --- sur stocks ",
"6594 --- sur créances ",
"6598 --- Autres charges provisionnées ",
"66 - CHARGES DE PERSONNEL ",
"661 -- RÉMUNÉRATIONS DIRECTES VERSÉES AU PERSONNEL NATIONAL", 
"6611 --- Appointements salaires et commissions ",
"6612 --- Primes et gratifications ",
"6613 --- Congés payés ",
"6614 --- Indemnités de préavis, de licenciement et de recherche d'embauche ",
"6615 --- Indemnités de maladie versées aux travailleurs ",
"6616 --- Supplément familial ",
"6617 --- Avantages en nature ",
"6618 --- Autres rémunérations directes ",
"662 -- RÉMUNÉRATIONS DIRECTES VERSÉES AU PERSONNEL NON NATIONAL ",
"6621 --- Appointements salaires et commissions ",
"6622 --- Primes et gratifications ",
"6623 --- Congés payés ",
"6624 --- Indemnités de préavis, de licenciement et de recherche d'embauche ",
"6625 --- Indemnités de maladie versées aux travailleurs ",
"6626 --- Supplément familial ",
"6627 --- Avantages en nature ",
"6628 --- Autres rémunérations directes ",
"663 -- INDEMNITÉS FORFAITAIRES VERSÉES AU PERSONNEL ",
"6631 --- Indemnités de logement ",
"6632 --- Indemnités de représentation ",
"6633 --- Indemnités d'expatriation ",
"6638 --- Autres indemnités et avantages divers ",
"664 -- CHARGES SOCIALES ",
"6641 --- Charges sociales sur rémunération du personnel national ",
"6642 --- Charges sociales sur rémunération du personnel non national ",
"666 -- RÉMUNÉRATIONS ET CHARGES SOCIALES DE L'EXPLOITANT INDIVIDUEL ",
"6661 --- Rémunération du travail de l'exploitant ",
"6662 --- Charges sociales ",
"667 -- RÉMUNÉRATION TRANSFÉRÉE DE PERSONNEL EXTÉRIEUR ",
"6671 --- Personnel intérimaire ",
"6672 --- Personnel détaché ou prêté à l’entreprise ",
"668 -- AUTRES CHARGES SOCIALES ",
"6681 --- Versements aux Syndicats et Comités d'entreprise, d'établissement ",
"6682 --- Versements aux Comités d'hygiène et de sécurité ",
"6683 --- Versements aux autres oeuvres sociales ",
"6684 --- Médecine du travail et pharmacie ",
"67 - FRAIS FINANCIERS ET CHARGES ASSIMILÉES ",
"671 -- INTÉRÊTS DES EMPRUNTS ",
"6711 --- Emprunts obligataires ",
"6712 --- Emprunts auprès des établissements de crédit ",
"6713 --- Dettes liées à des participations ",
"672 -- INTÉRÊTS DANS LOYERS DE CRÉDIT-BAIL ET CONTRATS ASSIMILÉS ",
"6721 --- Intérêts dans loyers de crédit-bail immobilier ",
"6722 --- Intérêts dans loyers de crédit-bail mobilier ",
"6723 --- Intérêts dans loyers des autres contrats ",
"673 -- ESCOMPTES ACCORDÉS ",
"674 -- AUTRES INTÉRÊTS ",
"6741 --- Avances reçues et dépôts créditeurs ",
"6742 --- Comptes courants bloqués ",
"6743 --- Intérêts sur obligations cautionnées  ",
"6744 --- Intérêts sur dettes commerciales ",
"6745 --- Intérêts bancaires et sur opérations de trésorerie et d’escompte ",
"6748 --- Intérêts sur dettes diverses ",
"675 -- ESCOMPTES DES EFFETS DE COMMERCE ",
"676 -- PERTES DE CHANGE ",
"677 -- PERTES SUR CESSIONS DE TITRES DE PLACEMENT ",
"678 -- PERTES SUR RISQUES FINANCIERS ",
"6781 --- sur rentes viagères ",
"6782 --- sur opérations financières ",
"6784 --- sur instruments de trésorerie ",
"679 -- CHARGES PROVISIONNÉES FINANCIÈRES ",
"6791 --- sur risques financiers ",
"6795 --- sur titres de placement ",
"6798 --- Autres charges provisionnées financières ",
"68 - DOTATIONS AUX AMORTISSEMENTS ",
"681 -- DOTATIONS AUX AMORTISSEMENTS D'EXPLOITATION ",
"6811 --- Dotations aux amortissements des charges immobilisées ",
"6812 --- Dotations aux amortissements des immobilisations incorporelles ",
"6813 --- Dotations aux amortissements des immobilisations corporelles ",
"687 -- DOTATIONS AUX AMORTISSEMENTS À CARACTÈRE FINANCIER ",
"6872 --- Dotations aux amortissements des primes de remboursement des obligations ",
"6878 --- Autres dotations aux amortissements à caractère financier ",
"69 - DOTATIONS AUX PROVISIONS ",
"691 -- DOTATIONS AUX PROVISIONS D'EXPLOITATION ",
"6911 --- pour risques et charges ",
"6912 --- pour grosses réparations ",
"6913 --- pour dépréciation des immobilisations incorporelles ",
"6914 --- pour dépréciation des immobilisations corporelles ",
"697 -- DOTATIONS AUX PROVISIONS FINANCIÈRES ",
"6971 --- pour risques et charges ",
"6972 --- pour dépréciation des immobilisations financières ",
"70 - VENTES ",
"701 -- VENTES DE MARCHANDISES ",
"7011 --- dans la Région ",
"7012 --- hors Région", 
"7013 --- aux entreprises du groupe dans la Région ",
"7014 --- aux entreprises du groupe hors Région ",
"702 -- VENTES DE PRODUITS FINIS ",
"7021 --- dans la Région", 
"7022 --- hors Région", 
"7023 --- aux entreprises du groupe dans la Région ",
"7024 --- aux entreprises du groupe hors Région ",
"703 -- VENTES DE PRODUITS INTERMÉDIAIRES ",
"7031 --- dans la Région", 
"7032 --- hors Région", 
"7033 --- aux entreprises du groupe dans la Région ",
"7034 --- aux entreprises du groupe hors Région ",
"704 -- VENTES DE PRODUITS RÉSIDUELS ",
"7041 --- dans la Région", 
"7042 --- hors Région", 
"7043 --- aux entreprises du groupe dans la Région ",
"7044 --- aux entreprises du groupe hors Région ",
"705 -- TRAVAUX FACTURÉS ",
"7051 --- dans la Région", 
"7052 --- hors Région",
"7053 --- aux entreprises du groupe dans la Région ",
"7054 --- aux entreprises du groupe hors Région ",
"706 -- SERVICES VENDUS ",
"7061 --- dans la Région", 
"7062 --- hors Région", 
"7063 --- aux entreprises du groupe dans la Région ",
"7064 --- aux entreprises du groupe hors Région ",
"707 -- PRODUITS ACCESSOIRES ",
"7071 --- Ports, emballages perdus et autres frais facturés ",
"7072 --- Commissions et courtages",
"7073 --- Locations", 
"7074 --- Bonis sur reprises et cessions d'emballages ",
"7075 --- Mise à disposition de personnel", 
"7076 --- Redevances pour brevets, logiciels,marques et droits similaires", 
"7077 --- Services exploités dans l'intérêt du personnel ",
"7078 --- Autres produits accessoires ",
"71 - SUBVENTIONS D'EXPLOITATION ",
"711 -- SUR PRODUITS À L'EXPORTATION ",
"712 -- SUR PRODUITS À L'IMPORTATION ",
"713 -- SUR PRODUITS DE PÉRÉQUATION ",
"718 -- AUTRES SUBVENTIONS D'EXPLOITATION ",
"7181 --- Versées par l'État et les collectivités publiques ",
"7182 --- Versées par les organismes internationaux ",
"7183 --- Versées par des tiers ",
"72 - PRODUCTION IMMOBILISÉE ",
"721 -- IMMOBILISATIONS INCORPORELLES ",
"722 -- IMMOBILISATIONS CORPORELLES ",
"726 -- IMMOBILISATIONS FINANCIÈRES ",
"73 - VARIATIONS DES STOCKS DE BIENS ET DE SERVICES PRODUITS ",
"734 -- VARIATIONS DES STOCKS DE PRODUITS EN COURS ",
"7341 --- Produits en cours ",
"7342 --- Travaux en cours ",
"735 -- VARIATIONS DES EN-COURS DE SERVICES ",
"7351 --- Études en cours  ",
"7352 --- Prestations de services en cours", 
"736 -- VARIATIONS DES STOCKS DE PRODUITS FINIS ",
"737 -- VARIATIONS DES STOCKS DE PRODUITS INTERMÉDIAIRES ET RÉSIDUELS ",
"7371 --- Produits intermédiaires ",
"7372 --- Produits résiduels ",
"75 - AUTRES PRODUITS ",
"752 -- QUOTE-PART DE RÉSULTAT SUR OPÉRATIONS FAITES EN COMMUN",
"7521 --- Quote-part transférée de pertes (comptabilité du gérant) ",
"7525 --- Bénéfices attribués par transfert (comptabilité des associés non gérants) ",
"753 -- QUOTE-PART DE RÉSULTAT SUR EXÉCUTION PARTIELLE DE CONTRATS PLURI-EXERCICES",
"754 -- PRODUITS DES CESSIONS COURANTES D'IMMOBILISATIONS ",
"758 -- PRODUITS DIVERS ",
"7581 --- Jetons de présence et autres rémunérations d'administrateurs ",
"7582 --- Indemnités d’assurances reçues ",
"759 -- REPRISES DE CHARGES PROVISIONNÉES D'EXPLOITATION",
"7591 --- sur risques à court terme ",
"7593 --- sur stocks ",
"7594 --- sur créances ",
"7598 --- sur autres charges provisionnées ",
"77 - REVENUS FINANCIERS ET PRODUITS ASSIMILÉS",
"771 -- INTÉRÊTS DE PRÊTS",
"772 -- REVENUS DE PARTICIPATIONS ",
"773 -- ESCOMPTES OBTENUS ",
"774 -- REVENUS DE TITRES DE PLACEMENT ",
"776 -- GAINS DE CHANGE ",
"777 -- GAINS SUR CESSIONS DE TITRES DE PLACEMENT ",
"778 -- GAINS SUR RISQUES FINANCIERS ",
"7781 --- sur rentes viagères ",
"7782 --- sur opérations financières ",
"7784 --- sur instruments de trésorerie ",
"779 -- REPRISES DE CHARGES PROVISIONNÉES FINANCIÈRES ",
"7791 --- sur risques financiers ",
"7795 --- sur titres de placement  ",
"7798 --- autres charges provisionnées financières ",
"78 - TRANSFERTS DE CHARGES ",
"781 -- TRANSFERTS DE CHARGES D'EXPLOITATION ",
"787 -- TRANSFERTS DE CHARGES FINANCIERES ",
"79 - REPRISES DE PROVISIONS ",
"791 -- REPRISES DE PROVISIONS D'EXPLOITATION ",
"7911 --- pour risques et charges ",
"7912 --- pour grosses réparations ",
"7913 --- pour dépréciation des immobilisations incorporelles ",
"7914 --- pour dépréciation des immobilisations corporelles ",
"797 -- REPRISES DE PROVISIONS FINANCIÈRES ",
"7971 --- pour risques et charges ",
"7972 --- pour dépréciation des immobilisations financières ",
"798 -- REPRISES D'AMORTISSEMENTS " ,
"81 - VALEURS COMPTABLES DES CESSIONS D'IMMOBILISATIONS ",
"811 -- IMMOBILISATIONS INCORPORELLES ",
"812 -- IMMOBILISATIONS CORPORELLES ",
"816 -- IMMOBILISATIONS FINANCIÈRES ",
"82 - PRODUITS DES CESSIONSD'IMMOBILISATIONS ",
"821 -- IMMOBILISATIONS INCORPORELLES ",
"822 -- IMMOBILISATIONS CORPORELLES ",
"826 -- IMMOBILISATIONS FINANCIÈRES  ", 	
"83 - CHARGES HORS ACTIVITÉS ORDINAIRES ",
"831 -- CHARGES H.A.O. CONSTATÉES ",
"834 -- PERTES SUR CRÉANCES H.A.O. ",
"835 -- DONS ET LIBÉRALITÉS ACCORDÉS ",
"836 -- ABANDONS DE CRÉANCES CONSENTIS ",
"839 -- CHARGES PROVISIONNÉES H.A.O. ",
"84 - PRODUITS HORS ACTIVITÉS ORDINAIRES ",
"841 -- PRODUITS H.A.O CONSTATÉS ",
"845 -- DONS ET LIBÉRALITÉS OBTENUS ",
"846 -- ABANDONS DE CRÉANCES OBTENUS ",
"848 -- TRANSFERTS DE CHARGES H.A.O ",
"849 -- REPRISES DES CHARGES PROVISIONNÉES H.A.O. ",
"85 - DOTATIONS HORS ACTIVITÉS ORDINAIRES ",
"851 -- DOTATIONS AUX PROVISIONS RÉGLEMENTÉES ",
"852 -- DOTATIONS AUX AMORTISSEMENTS H.A.O. ",
"853 -- DOTATIONS AUX PROVISIONS POUR DÉPRÉCIATION H.A.O. ",
"854 -- DOTATIONS AUX PROVISIONS POUR RISQUES ET CHARGES H.A.O. ",
"858 -- AUTRES DOTATIONS H.A.O. ",
"86 - REPRISES HORS ACTIVITÉS ORDINAIRES ",
"861 -- REPRISES DE PROVISIONS RÉGLEMENTÉES ",
"862 -- REPRISES D’AMORTISSEMENTS ",
"863 -- REPRISES DE PROVISIONS POUR DÉPRÉCIATION H.A.O. ",
"864 -- REPRISES DE PROVISIONS POUR RISQUES ET CHARGES H.A.O. ",
"865 -- REPRISES DE SUBVENTIONS D’INVESTISSEMENT ",
"868 -- AUTRES REPRISES H.A.O. ",
"87 - PARTICIPATION DES TRAVAILLEURS", 
"871 -- PARTICIPATION LÉGALE AUX BÉNÉFICES ",
"874 -- PARTICIPATION CONTRACTUELLE AUX BÉNÉFICES", 
"878 -- AUTRES PARTICIPATIONS ",
"88 - SUBVENTIONS D'ÉQUILIBRE ",
"881 -- ÉTAT ",
"884 -- COLLECTIVITÉS PUBLIQUES ",
"886 -- GROUPE ",
"888 -- AUTRES  ",
"89 - IMPÔTS SUR LE RÉSULTAT ",
"891 -- IMPÔTS SUR LES BÉNÉFICES DE L'EXERCICE ",
"8911 --- Activités exercées dans l'État ",
"8912 --- Activités exercées dans les autres États de la Région ",
"8913 --- Activités exercées hors Région ",
"892 -- RAPPEL D'IMPÔTS SUR RÉSULTATS ANTÉRIEURS ",
"895 -- IMPÔT MINIMUM FORFAITAIRE (I.M.F.) ",
"899 -- DÉGRÈVEMENTS ET ANNULATIONS D’IMPÔTS SUR RÉSULTATS ANTÉRIEURS ",
"8991 --- Dégrèvements ",
"8994 --- Annulations pour pertes rétroactives ",
"90 - ENGAGEMENTS OBTENUS ET ENGAGEMENTS ACCORDÉS",
"901 -- ENGAGEMENTS DE FINANCEMENT OBTENUS" ,
"9011 --- Crédits confirmés obtenus ",
"9012 --- Emprunts restant à encaisser",
"9013 --- Facilités de financement renouvelables", 
"9014 --- Facilités d'émission ",
"9018 --- Autres engagements de financement obtenus", 
"902 --- ENGAGEMENTS DE GARANTIE OBTENUS",
"9021 --- Avals obtenus",
"9022 ---bCautions, garanties obtenues", 
"9023 --- Hypothèques obtenues",
"9024 --- Effets endossés par des tiers", 
"9028 --- Autres garanties obtenues",
"903 -- ENGAGEMENTS RÉCIPROQUES",
"9031 --- Achats de marchandises à terme", 
"9032 --- Achats à terme de devises",
"9033 --- Commandes fermes des clients", 
"9038 --- Autres engagements réciproques", 
"904 -- AUTRES ENGAGEMENTS OBTENUS",
"9041 --- Abandons de créances conditionnels", 
"9043 --- Ventes avec clause de réserve de propriété", 
"9048 --- Divers engagements obtenus",
"905 -- ENGAGEMENTS DE FINANCEMENT ACCORDÉS", 
"9051 --- Crédits accordés non décaissés",
"9058 --- Autres engagements de financement accordés", 
"906 -- ENGAGEMENTS DE GARANTIE ACCORDÉS",
"9061 --- Avals accordés",
"9062 --- Cautions, garanties accordées",
"9063 --- Hypothèques accordées",
"9064 --- Effets endossés par l'entreprise",
"9068 --- Autres garanties accordées",
"907 -- ENGAGEMENTS RÉCIPROQUES",
"9071 --- Ventes de marchandises à terme",
"9072 --- Ventes à terme de devises",
"9073 --- Commandes fermes aux fournisseurs", 
"9078 --- Autres engagements réciproques",
"907 -- AUTRES ENGAGEMENTS ACCORDÉS",
"9081 --- Annulations conditionnelles de dettes", 
"9082 --- Engagements de retraite",
"9083 --- Achats avec clause de réserve de propriété",
"9088 --- Divers engagements accordés",
"91 - CONTREPARTIES DES ENGAGEMENTS",
"911 à 914 -- CONTREPARTIE DES ENGAGEMENTS OBTENUS, 901 à 904",
"915 à 918 -- CONTREPARTIE DES ENGAGEMENTS ACCORDÉS, 905 à 908",
"92 - COMPTES REFLECHIS",
"93 - COMPTES DE RECLASSEMENTS", 
"94 - COMPTES DE COÛTS",
"95 - COMPTES DE STOCKS", 
"96 - COMPTES D'ECARTS SUR COUTS PREETABLIS", 
"97 - COMPTES DE DIFFERENCES DE TRAITEMENT COMPTABLE",  
"98 - COMPTES DE RESULTATS",
"99 - COMPTES DE LIAISONS INTERNES"
	};
		lv = (ListView) findViewById(R.id.liste_comptes_tous);
        inputSearch = (EditText) findViewById(R.id.Recherche_tous);
        adapter = new ArrayAdapter<String>(this, R.layout.list_item, R.id.nom_compte, liste_comptes);
        lv.setAdapter(adapter);
        
        inputSearch.addTextChangedListener(new TextWatcher() {
             
            @Override
            public void onTextChanged(CharSequence cs, int arg1, int arg2, int arg3) {
                
				ArrayAdapter<String> edit3;
				edit = String.valueOf(cs);
				ArrayList<String> edit2 = new ArrayList<String>();

				if(edit.isEmpty()){

					edit3 = new ArrayAdapter<String>(Liste.this, R.layout.list_item, R.id.nom_compte, liste_comptes);
					lv.setAdapter(adapter);

				}
				else
				{
					for(int i=0;i<liste_comptes.length;i++){
						if(liste_comptes[i].toLowerCase().indexOf(edit) != -1){

							edit2.add(liste_comptes[i]);
						}

						edit3 = new ArrayAdapter<String>(Liste.this, R.layout.list_item, R.id.nom_compte, edit2);
						lv.setAdapter(edit3);
					}
				}

            }
             
            @Override
            public void beforeTextChanged(CharSequence arg0, int arg1, int arg2,
                    int arg3) {
                // TODO Auto-generated method stub
                 
            }
             
            @Override
            public void afterTextChanged(Editable arg0) {
                // TODO Auto-generated method stub                         
            }
        });
	}

	@Override
	public boolean onCreateOptionsMenu(Menu menu) {
		// Inflate the menu; this adds items to the action bar if it is present.
		getMenuInflater().inflate(R.menu.liste, menu);
		return true;
	}
	public boolean onOptionsItemSelected(MenuItem item){
		
		
		if (item.getItemId() == R.id.action_settings) {
       	startActivity(new Intent(this, About.class));
         }
		
		return super.onOptionsItemSelected(item);
		
	}
}
